import { useRef, useState } from 'react'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export default function LessonPDFExporter({ lesson, content = [] }) {
  const [exporting, setExporting] = useState(false)
  const contentRef = useRef(null)

  const exportPDF = async () => {
    if (!contentRef.current) return
    setExporting(true)
    try {
      const canvas = await html2canvas(contentRef.current, {
        scale: 2, useCORS: true, backgroundColor: '#0c0a15', logging: false,
      })
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = pdf.internal.pageSize.getHeight()
      const ratio = canvas.width / (pdfWidth - 20)
      const scaledHeight = canvas.height / ratio
      let y = 10, remaining = scaledHeight
      while (remaining > 0) {
        const pageHeight = Math.min(remaining, pdfHeight - 20)
        pdf.addImage(imgData, 'PNG', 10, y, pdfWidth - 20, pageHeight, undefined, 'FAST', 0)
        remaining -= pageHeight
        if (remaining > 0) { pdf.addPage(); y = 10 }
      }
      pdf.save(`${lesson?.title || 'lesson'}.pdf`)
    } catch (err) {
      console.error('PDF export failed:', err)
    } finally {
      setExporting(false)
    }
  }

  const plainContent = content.filter(b => ['heading', 'paragraph', 'code', 'mcq'].includes(b.type))

  return (
    <>
      <button className="pdf-btn" onClick={exportPDF} disabled={exporting}>
        {exporting ? 'Exporting...' : 'Download PDF'}
        <style>{`
          .pdf-btn {
            display: inline-flex; align-items: center; gap: 6px;
            padding: 7px 14px;
            background: rgba(6,214,160,0.08);
            border: 1px solid rgba(6,214,160,0.25);
            border-radius: var(--radius-full);
            color: #06d6a0;
            font-size: 0.82rem; font-weight: 600;
            cursor: pointer; transition: all var(--transition-fast);
            font-family: 'Inter', sans-serif;
          }
          .pdf-btn:hover:not(:disabled) { background: rgba(6,214,160,0.15); border-color: rgba(6,214,160,0.45); }
          .pdf-btn:disabled { opacity: 0.6; cursor: not-allowed; }
        `}</style>
      </button>

      {/* Hidden export layout */}
      <div ref={contentRef} style={{ position: 'absolute', left: '-9999px', top: 0, width: '800px', padding: '40px', background: '#0c0a15', color: '#f0eeff', fontFamily: 'Arial, sans-serif' }}>
        <h1 style={{ fontSize: 24, marginBottom: 8, color: '#c77dff' }}>{lesson?.title}</h1>
        {lesson?.objectives?.length > 0 && (
          <div style={{ marginBottom: 24, padding: 16, background: 'rgba(247,37,133,0.08)', borderRadius: 8, border: '1px solid rgba(247,37,133,0.2)' }}>
            <p style={{ fontSize: 12, fontWeight: 700, color: '#f72585', marginBottom: 8 }}>LEARNING OBJECTIVES</p>
            {lesson.objectives.map((obj, i) => <p key={i} style={{ fontSize: 13, color: '#9d93c4', marginBottom: 4 }}>• {obj}</p>)}
          </div>
        )}
        {plainContent.map((block, i) => {
          if (block.type === 'heading')   return <h2 key={i} style={{ fontSize: 18, marginTop: 24, marginBottom: 8, color: '#f0eeff' }}>{block.text}</h2>
          if (block.type === 'paragraph') return <p key={i} style={{ fontSize: 13, lineHeight: 1.7, color: '#9d93c4', marginBottom: 12 }}>{block.text}</p>
          if (block.type === 'code')      return <pre key={i} style={{ background: '#0a070f', padding: 12, borderRadius: 6, fontSize: 11, color: '#e2e8f0', marginBottom: 12 }}><code>{block.text}</code></pre>
          if (block.type === 'mcq')       return (
            <div key={i} style={{ background: 'rgba(76,201,240,0.05)', padding: 12, borderRadius: 6, marginBottom: 12, border: '1px solid rgba(76,201,240,0.15)' }}>
              <p style={{ fontSize: 13, fontWeight: 700, color: '#f0eeff', marginBottom: 8 }}>Q: {block.question}</p>
              {block.options?.map((opt, j) => <p key={j} style={{ fontSize: 12, color: j === block.answer ? '#06d6a0' : '#9d93c4', marginBottom: 4 }}>{String.fromCharCode(65+j)}. {opt} {j === block.answer ? '(Correct)' : ''}</p>)}
            </div>
          )
          return null
        })}
        <p style={{ fontSize: 11, marginTop: 32, color: '#4d4470' }}>Generated by Text-to-Learn — AI-Powered Course Generator</p>
      </div>
    </>
  )
}
